version: "3.7"

services:
  mongodb:
    image: mongo:latest
    container_name: db_mongo
    restart: always
    ports: 
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: lappis
      MONGO_INITDB_ROOT_PASSWORD: lappis
      MONGO_INITDB_DATABASE: mongo_database 
    volumes:
      - /mongo-db:/data 
    networks:
      - network

  application:
      image: app:final
      ports:
          - 8000:8000
      networks:
          - network
      build:
          context: src
          dockerfile: dockerfile

networks:
    network:
      driver: bridge
