\hypertarget{dockerfile}{}\doxysection{Referência do Arquivo C\+:/\+Users/\+User/\+Documents/\+Git\+Hub/\+Trabalho-\/\+Individual-\/2022-\/2-\/-\/\+Public/dockerfile}
\label{dockerfile}\index{C:/Users/User/Documents/GitHub/Trabalho-\/Individual-\/2022-\/2-\/-\/Public/dockerfile@{C:/Users/User/Documents/GitHub/Trabalho-\/Individual-\/2022-\/2-\/-\/Public/dockerfile}}
