name: Projeto-Final-GCES
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Configurando com python 3.8.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.8"
    - name: Instalando dependencias
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Testando com pytest
      run: |
        pip install pytest
        export PYTHONPATH=src
        pytest --cov
    - name: Executando o poetry
      run: |
        pip install poetry
        cd gces-2022-2-poetry
        poetry build